### ISSUE TITLE
unrecognised option 'wallet-dir'

### ISSUE THREAD

**Issue by 350054665** [EOSIO/eos#5742]
wulideMac-mini:Docker wuli$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
wulideMac-mini:Docker wuli$ docker run --name nodeos -p 8888:8888 -p 9876:9876 -t eosio/eos nodeosd.sh arg1 arg2
2018-09-19T09:28:37.390 thread-0   main.cpp:136                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >
std::exception::what: unrecognised option 'wallet-dir'

**Comment by firesWu** [comment]
you should remove it in config.ini.
This is the update of 1.3.0.
```
Unknown configuration items in config.ini will now error on startup (#5678)
Prior to 1.3.0 unknown configuration items in config.ini would be silently ignored. This behavior has been changed in 1.3.0 to an error that prevents startup of nodeos. Users with old auto-generated config.ini files may need to remove some options that are no longer available in nodeos for example wallet-dir or unlock-timeout
```

**Comment by 350054665** [comment]
> you should remove it in config.ini.
> This is the update of 1.3.0.
> 
> Unknown configuration items in config.ini will now error on startup (#5678)
> Prior to 1.3.0 unknown configuration items in config.ini would be silently ignored. This behavior has been changed in 1.3.0 to an error that prevents startup of nodeos. Users with old auto-generated config.ini files may need to remove some options that are no longer available in nodeos for example `wallet-dir`or `unlock-timeout`





wulideMac-mini:eos wuli$ nodeos -v
v1.2.5
wulideMac-mini:eos wuli$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
wulideMac-mini:eos wuli$ docker run --name nodeos -p 8888:8888 -p 9876:9876 -t eosio/eos nodeosd.sh -e --http-alias=nodeos:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888 arg1 arg2
2018-09-19T11:42:19.386 thread-0   main.cpp:136                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >
std::exception::what: unrecognised option 'wallet-dir'

**Comment by jgiszczak** [comment]
Try `docker run --name nodeos -v`.

**Comment by kenorb** [comment]
Same here:

```
>docker run --name nodeos -p 9999:9999 -p 9876:9876 -t eosio/eos nodeosd.sh -e --http-alias=nodeos:9999 --http-alias=127.0.0.1:9999 --http-alias=localhost:999
9
2018-09-21T19:51:13.641 thread-0   main.cpp:136                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >
std::exception::what: unrecognised option 'wallet-dir'
```

If the info aren't correct in https://github.com/EOSIO/eos/tree/master/Docker, please fix it.

**Comment by kenorb** [comment]
Then `EOSIO/eos` image should be fixed at https://hub.docker.com/r/eosio/eos/ as I'm using the latest one.

**Comment by leventatbjss** [comment]
Same error here @jgiszczak 
As @kenorb pointed, the docker container is what gets built at the README he mentioned.
Basically I followed the same instructions and got the same error. I have not specified any options in config.ini too.
After reading this here, I went into the config.ini and commented out the line as:
`# wallet-dir = "."`
That did not fix. Then I went into these:
`docker-compose-latest.yml`
`docker-compose.yml`
and removed
`--wallet-dir` options from there as well.
After all these changes, I removed docker container and docker images and rebuilt the container from scratch (takes some time on an i5 laptop tbh).
Still running into the same issue.

**Comment by qq6690876** [comment]
Same as @leventatbjss .

**Comment by hama** [comment]
Same issue

**Comment by r3lik** [comment]
same issue

**Comment by liguobao** [comment]
Same issue

**Comment by NMaslukov** [comment]
Same issue

**Comment by liguobao** [comment]
remove 'wallet-dir = "."' from https://github.com/EOSIO/eos/blob/master/Docker/config.ini
```
FROM eosio/eos
COPY config.ini /
```
docker build . 

it's work.

**Comment by NMaslukov** [comment]
@liguobao Hi, how to remove 'wallet-dir = "."' from foreign github?) Or how ot force docker to build from local repository?

**Comment by kenorb** [comment]
@jgiszczak Why can't you re-open this issue, if so many people have the same problem?

**Comment by jgiszczak** [comment]
@kenorb Reopening until the next release.  Fixed in the repo by #6021 and #5988.

**Comment by vegyraupe** [comment]
In case anyone else runs into this and needs a fix without building the whole image.

After an unsuccessful run ending with:
std::exception::what: unrecognised option 'wallet-dir'

Do:
docker cp nodeos:/opt/eosio/bin/data-dir/config.ini .
vi config.ini - COMMENT OUT wallet-dir or unlock-timeout
docker cp config.ini nodeos:/opt/eosio/bin/data-dir/config.ini

**Comment by andriantolie** [comment]
#6021 is merged so this issue should be fixed
